# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F4Iozi2aMsvGdEIpom-A1zSHDRaKM0yI
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv("employee_data.csv")
df.head()

import pandas as pd

df = pd.read_csv("employee_data.csv")

df.info()

df.describe()

df.isnull().sum()

print(df.nunique())

print(df['Gender'].value_counts())

print(df[df['Attrition'] == 'Yes'])

print(df.groupby('Department')['MonthlyIncome'].mean())

print(df.sort_values(by='MonthlyIncome', ascending=False))

print(df['JobRole'].value_counts())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 6))
sns.histplot(df["Age"], kde=True, bins=15, color='skyblue')
plt.title("Age Distribution of Employees")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(x="Attrition", y="JobSatisfaction", data=df, palette="Set2")
plt.title("Job Satisfaction by Attrition Status")
plt.xlabel("Attrition Status")
plt.ylabel("Job Satisfaction")
plt.show()

plt.figure(figsize=(8, 6))
sns.scatterplot(x="MonthlyIncome", y="JobSatisfaction", data=df, hue="Attrition", palette="coolwarm", alpha=0.7)
plt.title("Monthly Income vs. Job Satisfaction")
plt.xlabel("Monthly Income")
plt.ylabel("Job Satisfaction")
plt.show()

plt.figure(figsize=(8, 6))
sns.countplot(x="Gender", hue="Attrition", data=df, palette="pastel")
plt.title("Attrition by Gender")
plt.xlabel("Gender")
plt.ylabel("Number of Employees")
plt.show()

plt.figure(figsize=(10, 6))
sns.barplot(x="JobRole", y="PerformanceRating", data=df, palette="viridis")
plt.title("Performance Rating by Job Role")
plt.xlabel("Job Role")
plt.ylabel("Average Performance Rating")
plt.xticks(rotation=45)
plt.show()

gender_job_level = df.groupby(["Gender", "JobLevel"]).size().unstack().fillna(0)
gender_job_level.plot(kind='bar', stacked=True, figsize=(10, 6), color=['lightblue', 'lightgreen', 'orange', 'pink', 'lightcoral'])
plt.title("Job Level Distribution by Gender")
plt.xlabel("Gender")
plt.ylabel("Number of Employees")
plt.xticks(rotation=0)
plt.show()